version: "3"

services:
  shop-app-api:
    hostname: unicorn-shop-app-api
    image: unicorn-shop-app-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "4400:4400"
