version: "3"

services:
  shop-app-api:
    extends:
      file: ./compose.yaml
      service: shop-app-api
    env_file:
      - ./.env.local

networks:
  jumpserver:
    external: true
  unicorn:
    external: true
