POST http://localhost:4400/product/create
Content-Type: application/json

{
    "name": "John Doe",
    "price": 42
}

###

POST http://178.54.11.35:4400/order/webhook/mono/
Content-Type: application/json

{
  "name": "John Doe",
  "price": 42
}
